import { runFfmpeg } from "./ffmpeg.ts";

/**
 * Procedural placeholder assets, generated by FFmpeg itself. These are REAL files on disk —
 * a genuine PNG, a genuine silent audio track — used ONLY when no local AI backend is
 * configured (no ACF_IMAGE_BASE_URL / ACF_AUDIO_BASE_URL). They are always reported with an
 * explicit source tag ("procedural-placeholder") so they are never mistaken for AI output.
 * Their purpose is to let the renderer produce a real, playable MP4 today; swapping in a
 * ComfyUI/TTS backend replaces them with real generation and nothing else changes.
 */

/** Sanitize text for FFmpeg's drawtext (which treats %,:,\,' specially). */
function escapeDrawText(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/:/g, "\\:")
    .replace(/'/g, "’") // curly apostrophe avoids quoting hazards
    .replace(/%/g, "\\%")
    .replace(/\n/g, " ")
    .slice(0, 120);
}

export interface SceneCardSpec {
  readonly outPath: string;
  readonly title: string;
  readonly subtitle: string;
  readonly hexColor: string; // e.g. "0x1F8A8A" or "#1F8A8A"
  readonly width: number;
  readonly height: number;
}

/** Render a real PNG "scene card": solid brand-color background + wrapped scene text. */
export async function renderSceneCard(spec: SceneCardSpec): Promise<void> {
  const color = spec.hexColor.replace(/^#/, "0x");
  const title = escapeDrawText(spec.title);
  const subtitle = escapeDrawText(spec.subtitle);
  await runFfmpeg(
    [
      "-y",
      "-loglevel", "error",
      "-f", "lavfi",
      "-i", `color=c=${color}:s=${spec.width}x${spec.height}`,
      "-frames:v", "1",
      "-vf",
      [
        `drawtext=text='${title}':fontcolor=white:fontsize=${Math.round(spec.height / 12)}:x=(w-tw)/2:y=(h/2)-th:box=1:boxcolor=black@0.35:boxborderw=20`,
        `drawtext=text='${subtitle}':fontcolor=white@0.9:fontsize=${Math.round(spec.height / 22)}:x=(w-tw)/2:y=(h/2)+20`,
      ].join(","),
      spec.outPath,
    ],
    60_000,
  );
}

/** Render a real silent stereo audio track of the given duration (valid AAC-encodable). */
export async function renderSilentTrack(outPath: string, seconds: number): Promise<void> {
  const dur = Math.max(0.5, seconds).toFixed(2);
  await runFfmpeg(
    ["-y", "-loglevel", "error", "-f", "lavfi", "-i", "anullsrc=r=44100:cl=stereo", "-t", dur, "-c:a", "aac", outPath],
    60_000,
  );
}

/** Concatenate per-line audio files into one beat track, padded to an exact duration so the
 *  beat's audio length matches its video length. All inputs are real files; output is real. */
export async function combineBeatAudio(
  lineFiles: readonly string[],
  outPath: string,
  durationSec: number,
): Promise<void> {
  const dur = Math.max(0.5, durationSec).toFixed(2);
  const inputs = lineFiles.flatMap((f) => ["-i", f]);
  const labels = lineFiles.map((_, i) => `[${i}:a]`).join("");
  const filter =
    lineFiles.length > 1
      ? `${labels}concat=n=${lineFiles.length}:v=0:a=1,apad,atrim=0:${dur}[a]`
      : `[0:a]apad,atrim=0:${dur}[a]`;
  await runFfmpeg(
    ["-y", "-loglevel", "error", ...inputs, "-filter_complex", filter, "-map", "[a]", "-c:a", "aac", outPath],
    120_000,
  );
}

/** Render a real, gentle sine-tone "music bed" (honest placeholder when no music model). */
export async function renderToneBed(outPath: string, seconds: number): Promise<void> {
  const dur = Math.max(0.5, seconds).toFixed(2);
  await runFfmpeg(
    [
      "-y", "-loglevel", "error",
      "-f", "lavfi", "-i", "sine=frequency=220:sample_rate=44100",
      "-f", "lavfi", "-i", "sine=frequency=277:sample_rate=44100",
      "-filter_complex", "[0][1]amix=inputs=2,volume=0.15,atrim=0:" + dur + "[a]",
      "-map", "[a]", "-t", dur, "-c:a", "aac", outPath,
    ],
    60_000,
  );
}
