import { mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, isAbsolute, join, resolve } from "node:path";

/**
 * Where generated bytes (images, audio) are persisted. Real adapters hand raw bytes to an
 * ObjectStore and get back a durable URI to record on the EpisodeAsset. In production this is
 * S3/Backblaze; here a local filesystem implementation keeps the whole pipeline runnable.
 */
export interface ObjectStore {
  put(key: string, bytes: Uint8Array, contentType: string): Promise<string>;
}

export class FileObjectStore implements ObjectStore {
  readonly #root: string;

  constructor(root: string) {
    this.#root = isAbsolute(root) ? root : resolve(process.cwd(), root);
  }

  async put(key: string, bytes: Uint8Array, _contentType: string): Promise<string> {
    // Prevent path traversal from a provider-supplied key.
    const safeKey = key.replace(/\.\.+/g, ".").replace(/^\/+/, "");
    const path = join(this.#root, safeKey);
    const dir = dirname(path);
    if (!existsSync(dir)) await mkdir(dir, { recursive: true });
    await writeFile(path, bytes);
    return `file://${path}`;
  }
}
